defaultSettings:
  defaultReplicaCount: 2
  replicaAutoBalance: best-effort
  storageMinimalAvailablePercentage: 10
  storageOverProvisioningPercentage: 200

persistence:
  defaultClass: true
  defaultClassReplicaCount: 2

csi:
  kubeletRootDir: /var/lib/kubelet

preUpgradeChecker:
  jobEnabled: false
