apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://raw.githubusercontent.com/kubernetes/ingress-nginx/main/deploy/static/provider/cloud/deploy.yaml

patches:
  - target:
      kind: Deployment
      name: ingress-nginx-controller
    patch: |
      - op: add
        path: /spec/template/spec/nodeSelector/node-role
        value: worker
